services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: stripegym
      POSTGRES_PASSWORD: stripegym
      POSTGRES_DB: stripegym
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"  # ローカルアクセス用にポートを公開（競合回避のため5433に変更）
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U stripegym -d stripegym"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  app:
    build: ./backend
    ports:
      - "5001:5000"
    environment:
      - DATABASE_URL=postgresql://stripegym:stripegym@db:5432/stripegym
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend:/app
    working_dir: /app
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
    # 開発環境ではファイル変更を監視して自動再読み込み
    environment:
      - NGINX_ENTRYPOINT_QUIET_LOGS=1

volumes:
  pgdata:
