"""Add user_id columns to existing tables

Revision ID: 002
Revises: 001
Create Date: 2024-12-20 12:30:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '002'
down_revision = '001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add user_id column to ledger table
    op.add_column('ledger', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('ledger', sa.Column('product_name', sa.String(length=255), nullable=True))
    
    # Add user_id column to subscriptions table
    op.add_column('subscriptions', sa.Column('user_id', sa.Integer(), nullable=True))
    
    # Add foreign key constraints
    op.create_foreign_key('fk_ledger_user_id', 'ledger', 'users', ['user_id'], ['id'])
    op.create_foreign_key('fk_subscriptions_user_id', 'subscriptions', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove foreign key constraints
    op.drop_constraint('fk_subscriptions_user_id', 'subscriptions', type_='foreignkey')
    op.drop_constraint('fk_ledger_user_id', 'ledger', type_='foreignkey')
    
    # Remove columns
    op.drop_column('subscriptions', 'user_id')
    op.drop_column('ledger', 'product_name')
    op.drop_column('ledger', 'user_id')
    # ### end Alembic commands ###
