"""add processed_events table

Revision ID: 005_add_processed_events_table
Revises: 004_add_cancel_at_period_end
Create Date: 2024-12-20 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '005_add_processed_events_table'
down_revision = '004'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('processed_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('processed_events')
    # ### end Alembic commands ###
